### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by abe33** [atom/metrics#46]
[Enter steps to reproduce below:]

1. Create or open any file
2. Paste something inside it

**Atom Version**: 0.199.0-8c61a6b
**System**: Mac OS X 10.10.3
**Thrown From**: [metrics](https://github.com/atom/metrics) package, v0.46.0

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/metrics/lib/metrics.js:163

TypeError: undefined is not a function
  at Object.module.exports.getPackageName (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/metrics/lib/metrics.js:163:42)
  at Immediate._onImmediate (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/metrics/lib/metrics.js:139:126)
  at processImmediate [as _immediateCallback] (timers.js:369:17)

```

### Commands

```
     -0:08.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:03.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:02.2.0 cut-line:paste-line (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "minimap-symbols",
      "preview-tabs",
      "crosshairs",
      "coffee-compile",
      "travis-ci-status",
      "enhanced-package-list",
      "themed-settings",
      "tree-view-breadcrumb"
    ],
    "themes": [
      "one-dark-ui",
      "spacegray-dark-syntax"
    ],
    "audioBeep": false,
    "destroyEmptyPanes": false
  },
  "metrics": {
    "userId": "a677fee57f167fa48766293df30a3dc3309a25a6"
  }
}
```

### Installed Packages

```coffee
# User
Stylus, v1.0.0
Sublime-Style-Column-Selection, v1.2.3
atom-color-highlight, v3.0.9
bezier-curve-editor, v0.6.6
block-travel, v1.0.2
bug-report, v0.7.0
caniuse, v0.5.3
cut-line, v0.10.0
docblockr, v0.7.1
figlet, v0.4.0
file-icons, v1.5.5
highlight-selected, v0.9.1
language-generic-config, v0.2.0
language-haml, v0.20.0
language-jade, v0.4.0
language-sass, v0.38.0
linter, v0.12.2
linter-coffeelint, v0.2.3
minimap, v4.8.0
minimap-bookmarks, v0.1.0
minimap-color-highlight, v4.1.3
minimap-find-and-replace, v4.2.0
minimap-git-diff, v4.1.2
minimap-highlight-selected, v4.2.3
minimap-selection, v4.2.0
php-twig, v3.0.0
pigments, v0.2.0
project-palette-finder, v2.4.17
red-wavy-underline, v0.3.0
spacegray-dark-syntax, v0.2.0
tabs-to-spaces, v0.10.0
tree-view-open-files, v0.2.3
typewriter, v0.3.3
view-tail-large-files, v0.1.14
white-cursor, v0.6.0
zentabs, v0.8.4

# Dev
atom-color-highlight, v3.0.9
bezier-curve-editor, v0.6.6
deprecation-cop, v0.10.0
figlet, v0.4.0
minimap, v4.8.0
minimap-bookmarks, v0.1.0
minimap-color-highlight, v4.1.0
minimap-find-and-replace, v4.2.0
minimap-git-diff, v4.1.2
minimap-highlight-selected, v4.2.3
minimap-selection, v4.2.0
pigments, v0.2.0
project-palette-finder, v2.4.17
settings-view, v0.195.0
```

**Comment by KapuzenSohn** [comment]
I have the same issue

**Comment by lee-dohm** [comment]
I got this error on Atom v0.199.0-8c61a6b on Mac OS X 10.10.3 after installing the [space-underscore package](https://atom.io/packages/space-underscore) and using the <kbd>Shift+Space</kbd> keymapping to enter an underscore.
